### ISSUE TITLE
Add github.io to the default whitelist

### ISSUE THREAD

**Issue by ashemedai** [chrisparnin/docsight#5]
Github recently announced their github.io domain for webpage hosting for projects, since people use this to host documentation for their projects as well, including a default entry for this in the whitelist makes sense.

**Comment by chrisparnin** [comment]
I wasn't sure at first to include github because of the wide possible scope, but now realizing this is a weekly if not daily resource I personally use.

Addressed in latest commit(s) and published in chrome store as 1.0.8
